# Generated by Django 5.0.1 on 2024-01-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smt_management_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localfile",
            name="upload_type",
            field=models.CharField(
                choices=[
                    ("article", "Article"),
                    ("carrier", "Carrier"),
                    ("board", "Board"),
                ],
                max_length=50,
            ),
        ),
    ]
