# Generated by Django 5.0.1 on 2024-05-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={},
        ),
        migrations.RemoveField(
            model_name='localfile',
            name='delimiter',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='localfile',
            name='_delimiter',
            field=models.CharField(choices=[(',', 0), (';', 1), ('\t', 2)], default=',', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localfile',
            name='lot_number',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='lighthouse_A_green',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='lighthouse_A_yellow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='lighthouse_B_green',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='lighthouse_B_yellow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='manufacturer_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='provider1_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='provider2_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='provider3_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='provider4_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='provider5_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='boardarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smt_management_app.article'),
        ),
        migrations.AlterField(
            model_name='job',
            name='finish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
