# Generated by Django 5.0.1 on 2024-05-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_management_app', '0002_alter_manufacturer_options_alter_provider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
