# Generated by Django 5.0.1 on 2025-08-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smt_management_app', '0003_board_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='COM_baudrate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='COM_timeout',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
